# Generated by Django 5.2.16 on 2026-08-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
