# Generated by Django 5.2.16 on 2026-08-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments_api", "0002_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
